### ISSUE TITLE
Any chance of merging with existing Python Interface

### ISSUE THREAD

**Issue by creedda** [ianlevesque/smartblinds-client#2]
Any chance of merging some of your code in with https://github.com/dnschneid/pysmartblinds?

I was thinking of forking some of your code in. But its yours so I figured I would bring it to your attention and see if you wanted to merge your control method in. It works great!

**Comment by ianlevesque** [comment]
I think fundamentally the approach is too different. pysmartblinds does direct BTLE communication instead of using the bridge. I think they could benefit from getting the auth keys from the API like I do though instead of needing to capture them.

**Comment by ianlevesque** [comment]
That said it’s permissively licensed on purpose so don’t let me stop you from repurposing.
