### ISSUE TITLE
Error if more than 7 blinds

### ISSUE THREAD

**Issue by jtinst** [ianlevesque/smartblinds-client#4]
If the array passed to get_blinds_state() contains more than 7 blinds, the following error is produced: 

> Traceback
>  (most recent call last):
>   File "jblinds.py", line 11, in <module>
>     states = client.get_blinds_state(blinds)
>   File "/home/pi/smartblinds-client/smartblinds_client/smartblinds.py", line 144                                                                                  , in get_blinds_state
>     return self._parse_states(response)
>   File "/home/pi/smartblinds-client/smartblinds_client/smartblinds.py", line 169                                                                                  , in _parse_states
>     for blind_state in response['data'][key]:
> TypeError: 'NoneType' object is not iterable

Doing a bit of digging, it seems that the bridge was returning the following error message: 

> {'data': {'blindsState': None}, 'errors': [{'path': ['blindsState'], 'message': 'Bridge only supports up to 7 commands at a time', 'locations': [{'line': 3, 'column': 21}]}]}

If I change the example script as follows, the problem is resolved (albeit very inartfully, I have basically zero python skills): 

> blinds1 = [blinds[0], blinds[1], blinds[2], blinds[3], blinds[4], blinds[5]]
> blinds2 = [blinds[6], blinds[7], blinds[8]]
> 
> states = client.get_blinds_state(blinds1)
> print(states)
> 
> states = client.get_blinds_state(blinds2)
> print(states)

If someone could fix this in a nicer way that scales, I sure would appreciate it.

**Comment by ianlevesque** [comment]
Thanks for the detailed report! Can't promise a fix right away but when I get a chance I'll address.
